# Generated by Django 4.2 on 2023-04-05 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('std', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'class',
            },
        ),
        migrations.CreateModel(
            name='SubjectsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.ImageField(upload_to='subject')),
                ('std', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_subjects', to='app.classmodel')),
            ],
            options={
                'db_table': 'subject-name',
            },
        ),
        migrations.CreateModel(
            name='NotesModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.URLField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_notes', to='app.subjectsmodel')),
            ],
            options={
                'db_table': 'notes',
            },
        ),
    ]
