# Generated by Django 4.2 on 2023-04-05 20:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('chapter_name', models.CharField(max_length=50)),
                ('link', models.URLField()),
            ],
            options={
                'db_table': 'chapter',
            },
        ),
        migrations.RenameField(
            model_name='subjectsmodel',
            old_name='name',
            new_name='subject_name',
        ),
        migrations.DeleteModel(
            name='NotesModel',
        ),
        migrations.AddField(
            model_name='chaptermodel',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_notes', to='app.subjectsmodel'),
        ),
    ]
